# Generated by Django 3.2.12 on 2022-05-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realestate',
            table='real_estate',
        ),
    ]
