# Generated by Django 3.2.12 on 2022-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_realestate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Sold')], default=1),
        ),
    ]
