# Generated by Django 3.2.12 on 2022-06-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220603_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='type_lease',
            field=models.IntegerField(blank=True, choices=[(1, 'Cho thuê nhà riêng'), (2, 'Cho thuê căn hộ chung cư'), (3, 'Cho thuê biệt thự, nhà liền kề'), (4, 'Cho thuê nhà mặt phố'), (5, 'Cho thuê shophouse, nhà phố thương mại'), (6, 'Cho thuê nhà trọ, phòng trọ'), (7, 'Cho thuê văn phòng'), (8, 'Cho thuê cửa hàng, ki ốt'), (9, 'Cho thuê kho, nhà xưởng, đất'), (10, 'Cho thuê đất'), (11, 'Cho thuê loại bất động sản khác')]),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type_sell',
            field=models.IntegerField(blank=True, choices=[(1, 'Bán nhà riêng'), (2, 'Bán căn hộ chung cư'), (3, 'Bán biệt thự, nhà liền kề'), (4, 'Bán nhà mặt phố'), (5, 'Bán shophouse, nhà phố thương mại'), (6, 'Bán đất nền dự án'), (7, 'Bán đất'), (8, 'Bán trang trại, khu nghỉ dưỡng'), (9, 'Bán kho, nhà xưởng'), (10, 'Bán loại bất động sản khác')]),
        ),
    ]
