# Generated by Django 3.2.12 on 2022-06-01 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_address_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_real_estate', to='users.realestate'),
        ),
    ]
