# Generated by Django 4.0.4 on 2022-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='realestateinfor',
            name='status',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
