# Generated by Django 4.0.4 on 2022-05-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('user', '0002_rename_profile_id_userprofile_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_street', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=5)),
                ('full_address', models.CharField(max_length=256)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.country')),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.district')),
                ('province_city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.provincecity')),
                ('ward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.ward')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.RemoveField(
            model_name='realestateinfor',
            name='location_id',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='realestateinfor',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
    ]
